name: olist_dbt

profile: olist_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

#seeds:
#  olist_dbt:
#    +schema: raw

models:
  olist_dbt:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
